# Generated by Django 5.1.2 on 2024-10-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brico_depot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_edit_comment', 'Can edit comment'), ('can_delete_comment', 'Can delete comment'), ('can_view_comment', 'Can view comment')]},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_edit_post', 'Can edit post'), ('can_delete_post', 'Can delete post'), ('can_view_post', 'Can view post')]},
        ),
    ]
