# Generated by Django 5.1.2 on 2024-10-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brico_depot', '0002_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
