# Generated by Django 5.1.2 on 2024-10-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brico_depot', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
